#! /bin/sh

case $1 in 
    start)
        echo "Loading aesd char driver"
        aesdchar_load
        ;;
    stop)
        echo "Stopping aesd char driver"
        aesdchar_unload
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0