#! /bin/sh

case $1 in 
    start)
        echo "Loading drivers"
        scull_load
        ;;
    stop)
        echo "Stopping drivers"
        ;;
    *)
        echo "Usage: $0 {start|stop}"
    exit 1
esac

exit 0